version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions-maintenance:
        applies-to: version-updates
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "helm"
    directory: "/application/photobooth-api"
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "helm"
    groups:
      photobooth-api-chart-maintenance:
        applies-to: version-updates
        patterns:
          - "*"
      photobooth-api-chart-security:
        applies-to: security-updates
        patterns:
          - "*"
