apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tls-proxies
  namespace: websites
spec:
  chart:
    spec:
      chart: ./application/tls-proxies
      interval: 1h
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 30m
  maxHistory: 5
  releaseName: tls-proxies
  timeout: 5m
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: tls-proxies-values
      valuesKey: values.yaml
