# version: v3.0.0

context= "home-server-infra"

[metadata]
  org = "bronneberg.org"
  maintainer = "Patrick (patrick@bronneberg.org)"
  description = "Basic infrastructure to be installed on home kubernetes cluster"
  notes = "This requires the bare cluster to be provisioned and the kubecontext to be defined as a prerequisite"

[settings]
  kubeContext = "homeserver"
  globalMaxHistory= 5

[namespaces]
  [namespaces.cert-manager]
    protected = true
  [namespaces.websites]
    protected = false
    [namespaces.websites.labels]
      env = "production"

[helmRepos]
  jetstack = "https://charts.jetstack.io"
  # stable = "https://kubernetes-charts.storage.googleapis.com"

[apps]
  [apps.cert-manager]
    namespace = "cert-manager" 
    enabled = true 
    chart = "jetstack/cert-manager"
    version = "v0.16.1"
    protected = true
    priority= -2
    wait = true
    timeout= 300
    [apps.cert-manager.hooks]
    postInstall="cert-manager.issuers.yaml"
    [apps.cert-manager.set]
    "installCRDs"= "true"