# Default values for tls-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  targetPort: 8080

endpoint:
  ip: ""

ingress:
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
  hostnames: []
