# Default values for tls-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  targetPort: 8080

endpoint:
  ip: ""

ingress:
  annotations:
    kubernetes.io/ingress.class: "traefik"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
  hostname: ""

