apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
  - custom-templates.yaml
  - github-oauth.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: oauth2-proxy-values
    files:
      - values.yaml
  - name: oauth2-proxy-runtime-values
    files:
      - values.yaml=runtime-values.yaml
generatorOptions:
  disableNameSuffixHash: true
