apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: oauth2-proxy-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
