apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: actions-runner-system
type: Opaque
stringData:
  github_token: ENC[AES256_GCM,data:1I8spPykTkQu1XMqrqflgX3G,iv:YWUKxBjtxRmf12rdXFBMhDHKqNGTDbp4dk9WmiL69Bo=,tag:j2LECYubiBqMQ56cEh6UWg==,type:str]
sops:
  age:
    - recipient: age1gtjn7ra9z50kyzfxlnrthq44msj44tqgkyawafps450w820mk4vql8mgpv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Wm85ZElDM2RFTDBKeEti
        T0RxTU96WVRmczNHc3dMWHFNdEtJUDh3UEFJCkU0ZE94RDZOUEQ1Sm1BZVBWOHoy
        bEpXSnFsYTg4T243M3lSM0tFUm1HOXMKLS0tIC9KdU40c2hEcXNaQTUyWHFFZ2Zm
        V1dwLytsMkcyODJsMDFCUTJRTVVGYkUKHwQemom0F7RcTmhdT+PGnK8ZHAJi7Q+j
        JAA7cSvvsCRF2Xw5dKVu9PPmuUhqxmQZo1AV1djItLJSuaAt0NJUMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-14T12:44:45Z"
  mac: ENC[AES256_GCM,data:aJgjXPBPCsAsPb5OjF9yC3CFg/1ihera7Z3D0nUOnX79Pfw1wFQGXmGh8ZqoQcms+TyNJx1geL9E7IvWYITK+QIJgVjC3M051Aqfi6HHCdcbu8V86hrF1EV/+j9rPIXT8L7rppSOZhUy8fV7tMwc8KRiLejyVcnvQeCCIq3Enmo=,iv:/r875tEIYO3UoFLCY0rZlDu4DbeA6LonxEWD3AVctpk=,tag:uUVlBycEz3rZ9/YvD2aw2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
