apiVersion: v1
kind: Secret
metadata:
  name: homeassist-values
  namespace: homeassistant
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:FWGNj84xDNfIi+9I90Av1OQiLAgGT8zlzVbuZuHLyG7yciTaaHLFiH+GeGAqPnD1EiMvKTCNhIIxNFcwdo0fSA/8culN+Y4cYcPrhI88aI0ez8a4bdIgR7dZRRjQ/pdpJ3bvEIYcKAFt8q/IIR/TjlnUqdoJ8OrimRMjRHVr8EGskkQYzyUVKRj4jmi+c7qeHn94kzT0/3XNOrt98gUWrdE73pAdWsnRcIrGG3Nh/Plo21huKCvrh+oUP06lD7/R58QiX6uR1K7NWTP8Nt0yWJJ6rWNSfhgGWnZ/KlZ1G9n6+eXVUCz/IhA8+lT7u7uBDuPUZU9QrbW7K5QgnTTieisXBB/GOJP4SoxcqfQX1V35CBlzc1Y3QjY0cPmJaH1EB9T+Dl9nK02Q+VYthGXcRCe7Gtvc6iAlBTjDIUQwjtuDqtplgiRU0dTE2mKp8tI6IMPOgyHko0teWgHyIY+8Ghi5O7N58TTDTWBpT2tpTnx8hZn3kWMKWYnOxdjmQ5pKIZPycN6EV1fa03SA/GlVJKbZF44NUISpxtVQz4o1prUMehtOhvnUf53bJ3mQF3w50jC/2K/9etrLDZxyfK3u7E0WTi9nsisAg761E/tF52xvsU09Gw9k9tbGp62FDZqGbnxp6rgIqQiWQKSTfuhWlk+bvqiNs3fDn5bw/ZAGvIALF9XuYwHx1Wk3rMO138NUCNQy7xoky7Q51emBRctQ,iv:Wvs3tGrilak0i8/YED1GaaI76BWd1e8jSEh1eKTTdSw=,tag:KMdePqTtTBgCRcDf6paXgw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWDg0alNLdHMwWHEveXVZ
        MWovZ2EvN2lJdkZtNVQ2SVRGK3dodk85bzNnCnZlSXJmVGkvSDFNZlhOWGdtaW91
        NEJLV1NtNmdVZEJCaG5kc2gxQTB3ZW8KLS0tIE0zVFF3a0toY28yT3pYTzFQMDlQ
        ZGhvRDFPS1dyMXkyKyt4TmMzYXRjRXMKxtzjMjSSbETi8r6oLsVXP7YlcNJj5MXN
        q23oLvsqf8KcXp34lC6Elp/WB2hUUTeCXd0j7DX6FYNui3C4OnkWvw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gtjn7ra9z50kyzfxlnrthq44msj44tqgkyawafps450w820mk4vql8mgpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T06:11:39Z"
  mac: ENC[AES256_GCM,data:CW71nsYQdu2VbdzXGOp+XROxu/vKuJhAZ0QCYki/AehUKi2AZcFbpTXvd9HvkgZPEWT2qOPMG9DzXfUmuacc00IKPG2I3pwkbMrp0TSlJWrWpaJULF4hPPBoO9CiRSGa6NrzhRCsOa/kos3Jc4UA2VcI+GylnquRxgn80gMCJ+w=,iv:988uxvxcg/7vjNljHxQ0iXomBd0WWANxco8Ssw5gmR0=,tag:ZgBegIfSX2wdgm30uYVnkw==,type:str]
  version: 3.13.3
