apiVersion: v1
kind: Secret
metadata:
  name: homelab-autoscaler-nodes
  namespace: homelab-autoscaler-system
type: Opaque
stringData:
  nodes.env: ENC[AES256_GCM,data:SZAWm5DVj4Xi85hIkE5Axr+uZy4XrUbHwkDFL0k0OpEqAMvEW9gQgcx46AhUfW05VFq/Ow4s2eb99l++D1Or1i4AvdbvBIBDFTYblFw0NmqMoIrOOhwKJfzEo6E51d0c/DNTp9SIykvoGwa0w72XYcwV+jc1UKJANT2ptCfwActMxX7fqFV+fslyphicaRDJbRexkbL5kEN4fEvvv6k0+TSELE8jGzs8WyAwkJSg2bkrHaEtSiP6SXjjuokw4gyn8fJ0W+dpGVuu5HKz+i5Yx7OPX/YcQDu2hsVNXPzIIUUp5CzAETGqCzlmDw81bFzo4Pn/Zzz/BgX4eywQxlaZyS0jhFClsixJ5NHFUpUYJoRa9TZ32Vk+i0BCyuAUlC8HFzRwd/VjATZM6DDNar5GkN+w+gy+5yP42EdMV4iVk+FwTil4navzs4D+qK9BO6zStSgZ+/LyElzdGPAzfRPVIhpZiFSUVpanbCjEdkTgiHOCpUiL4QBPAKb++KbcK/lcxI1Cmx2Radc0nRv/KCHv4Nu2LN+rGMSPAQ72Sj7/sHQhUQOMe4z+LgQ/iBllBHAJolxY0cQ+D0W/wyYa2XDHuRjL+nYE+lmtrSCxVlwFY7Jk9eRY1h1Pw+MtkfFEqd+naItCXAVFiiGipuBiQaIzbL+TXoMyvW46Vj1FqE3OJ2UCB0P9VaYJ70ilgyeWl0l04o3V+Q==,iv:of5llvBxZ+bL4FDKRXTMx+VWCcHO+ZKBcEWbJRCVfbY=,tag:a6inDjmNgWwNWFFb+mbutA==,type:str]
  ssh_public_key: ENC[AES256_GCM,data:bSGev7EbQ59FRYK0HaEBHSGpYhVC6FIZTVXhzbUGIV8Kd45WC4dnCnZJTBcr5tjZI98BGQ97qqrC6bI7olhIxdsVip7iJzhm0cuCvuFnT9BKODKdD4EwgJe/VFLcZPG69ckwk3+/ZYw72hOEvQ==,iv:/0KBIBWT0dT7pg64Dc0oh21SPBiFdNmuZc7Xd0LZ/b4=,tag:vf07qDAHkskm/A+iyxfpaA==,type:str]
  ssh_private_key: ENC[AES256_GCM,data:P8MpYL7lvcuZJW2CbgrBqAMbB+l78QWPb91ncgh9PfnnHal1UR/qbD2do1C9j3p+2i7C7x6q3XPSUXPDLz9OZRDupQDSu9ovowwtrrKPOyWSfwQ0QhTd8lCR3r3PmHzJBggKSeK2fPEbH1e3/q/zMmbW8Xzq0sVh5qxJPvkA+z5/u9R62fw5Qr/vPWu/sXPl66+SuyubjSX0+d0ZWElmwyUR2EvdFKuOunQ98H1yDNSqCp2tOsLRcU7tMNh08FOSkKANmI/9aIXbqeq3L+G8Y2tC5voOPI8Hv9kLTuXz/cb+Um7mWXq12njJTfM5ZO3GzgI975RmftXuwndW/KykqghR5RMaVPEZbJ0iU3nXYI8nV89LjVyy4pjD/Q8KuieI9WSekY6KRFdDPX9Uup5w9hfFeV2UNGWXEt7P4TRB2OyA3YMGXFJOryeS49tYiDwLCg6lG4frRskxoefYZOjY3yDFxCYrPg0dAG2pleXeWZWb6wnjs62y6uJbHt85qOQDx2vBvzeXInoUm5UdgxDWYVCk0IIGlOXyNioWNx5+n3j/Q8Y=,iv:YLXrljHmIO66dVzws94sqyOI+oa2mxDYJsSRQpkKgQE=,tag:YkqvJJ7SazikphtVa+ozbQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRM1htbjQyTnVlWkRrOVR1
        Z1ZkeGxNR1BzdWZUZTl3WUx4L3NNTGpUTG1NCmFCNGV2TTJmelYzU3F4bCthWWxi
        c3ozdWhHNFpWL1JzZ0lwZHE2Z2ZDcm8KLS0tIDFTc0FPMFpCUUpoYld4OGZVZkNO
        Y09JaDRyd2J4MEdFaGQyeVpCTmhnRkEKYBNt15nWn2+IRxI0pNOgRyFF030jnj75
        YJd87tG+LyQ/6auBlVX3pcM8amsUWArkDHCUUNJDm4xifUUZaONWiw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gtjn7ra9z50kyzfxlnrthq44msj44tqgkyawafps450w820mk4vql8mgpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-21T15:00:51Z"
  mac: ENC[AES256_GCM,data:Jsou0rZY6TuH+PGlIiQN2QzCbIRHCV+iW6+UlhAtJm/AJkuOZe6PB28WzeWHJxJXiOPGHu1oTUB115WwCaUCafELxuz3SU8hEUJEIhSFzZJpIZWoWSQ5gAt0c5nbT3/dx7jP0UhnnVeV7Qi5EXK3zdQcmqfKH4GL/ffQNwP+D6U=,iv:As88FBaaUgJPybNHoSqwLM6Q0offS7j/8fzPcU/yaI8=,tag:GXgDTBFRoKLj0N5AhBAvAg==,type:str]
  version: 3.13.1
