apiVersion: v1
kind: Secret
metadata:
  name: homeassist-values
  namespace: homeassistant
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:ZqiOMmMDVJ2LCW4mkTQSW74+EQk4S47MbE3dssjhv5b1EtuZjC1SG62za9buGMdTjUbR61roAZSPlOftBt4dGfEpqXLfTdfpEwSejGejUynelXvKvUbrPfDmHs+Vkpys9sCfusdN6cFxCN6vIbA2qsvcECaQuDeacWcS66Dwx7t9pNR58G7NkJrtZhyJdIvR6DhieD+x+k4UnZwBaHIcPmIs9/6mS3KLO1yheVosfB30v+8AEqjcIvQA/q5XHTxX85XT81PhhB+KI2BgJyD1EYxBCcB/wyZBnrRevJ7+kFjpINZzM/XgfPOtcsD69m1Uj9SAWnvR29KIUrYhqXVanW9HGeh8ccb2vGldQmvdTR44YuHXr0utJNUcJcYX738roLVUgeJ+h0HHTj44qw3EVzzCzfoY21QTKPK070svNNZWd/8gl5rnYaQZETud7CZQflxx2WqM81TOgW2ClMyC1pVKdJalqBxoMLXv4Ie5xOm0O0Qc57op7qA+ppEKTeB3H5i0AKBCWfUFPruI7NUYEk4Y6XRdiDc3MI3Tips9CYPdUxJV8V5VsPE7PtLPCnTEEIy8RW/7CJtYAn854RTd+M1ZEza8jEzBfbNlRM1WhE1Muc7RjCFUobb/Sc0LiVryu5pyKizlfE1gdV5SIOnwtOLNuym4I3v+zW98Qy4O7CA0TfElT7hmEebau65XzbbWcGh/0zGo/ZawW7DpKwZUvkjXb6vD38grg9BbX9TApeqFbQ==,iv:wrem8OV1f0jOyVmaZktfCVBJGbFJ4v6B61oYo5OwJBc=,tag:NHOKVHBWEW/BEUKUeKFUzA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhY3FaRDB4bHprU2dsS042
        eVQ2YWZQdTg1ZmlNQTZhSFZicEE5bmJOcml3CjEwckdwaFRXdEx0N0ZML1R4Mmlq
        RWdHTXRtTG5XZkVjbFJWVzA0OVhyN0kKLS0tIFpRcGVmRU9VcWtkTGtBWXhUVkFN
        eEl6aE1NU1ViNjZVM00wNWJMdHV6NzAKXUcUM2CilC5xSG7RhFcsO3gnkDYDv9zK
        ZvOy+J/yURSB74bsy6c0Fy9xFxrFJgnvtl10gNwTCnOjk++UjbJflA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gtjn7ra9z50kyzfxlnrthq44msj44tqgkyawafps450w820mk4vql8mgpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-09T20:36:28Z"
  mac: ENC[AES256_GCM,data:pGh1hocDhe1MF/oiecsP07J9G+nG2mXjwyA6hdgQs00KfYz0XxJJ7XTnoUpV9UAJNvcWb/b7axmVjKvJ1hteUQJhxtrN6ehcdYhLZBFS8eU5Wv1WGscy5u3N6fDpNa0MhYVWcd3laARMMvqatNKe7Y5zckZMyXeuj5DfEMGCvQo=,iv:+/h8upj9e8ER2Qjuf+3D/5MCcRKjm0NSxq14dESl/JM=,tag:zZkQ8YYGEaeLf80sHqQYnw==,type:str]
  version: 3.13.0
