apiVersion: v1
kind: Secret
metadata:
  name: homelab-autoscaler-nodes
  namespace: homelab-autoscaler-system
type: Opaque
stringData:
  nodes.env: ENC[AES256_GCM,data:ucuQA3184STexjCtA7orXSGBmnNvpToC0M7YvlP85ZAhc0IkOBxCScCzHo5qBHQLJhqcs/z3Pnn4Lyh23Y6JP2kW5UpvNpbaOJ+D9g1xpQQRIvTJOmqEUP+HC0hSp5HJJ/lr1BQySMUKsqrRo4TAyn2aSZGEvjYS413p+cG8H+UuA+ZmEvjL1YfHlw4uRhQf7D2W6hRrp8dPF6lHJ9UGnInpNaYY3O/xQH76BfktJ7UcoO/2QzhTp32ankmw/ySkrhh0u4RuHnalOdHdRZNh1A2ULuuit4L7N03Uvig857EjrX1A3RR5QmbRyen6ai/jhFDDGS5aQtUExW2ZD96OE6aDkscaJCgmXTpWuy2vv3YxTuKNYQjhzyJvMjkZxAAUr4ZZObE8O38SBeV5n8UQ8SYTFarWsSE+Vxb5/LSRIwJGtGH2VHLFGjZd6tvZOo+kru730my7dx1g/GD+y/+K8YJNxOE5G1JP2KIYQ3BOSaGCDm7+iuSpg87XDQIrCeI8ZaOfIpXdnwPV1kCDzdYWBb8mO6TBsS63+TV1QIALV7M19kVu8/XZUSLtvUAnVFR7QWWGeTNP4uxZ+WmumvnOEDMw9XqlUN/hAq6D/buzsbt7ZII9LSPqUOnqmAvMZhRSS7HxLPe+cuBf57lEmtYzNF3/oMAiHJtIbAyod2hSQSmXLwIZXfdazcyM1GE3fiPTgg==,iv:K8Gbuw/1yjHcRez8AnRASWylTjOMgdKo0l/1TPwdSJo=,tag:GMUMFuqZCa0NVtZ6G7xfaQ==,type:str]
  ssh_public_key: ENC[AES256_GCM,data:bSGev7EbQ59FRYK0HaEBHSGpYhVC6FIZTVXhzbUGIV8Kd45WC4dnCnZJTBcr5tjZI98BGQ97qqrC6bI7olhIxdsVip7iJzhm0cuCvuFnT9BKODKdD4EwgJe/VFLcZPG69ckwk3+/ZYw72hOEvQ==,iv:/0KBIBWT0dT7pg64Dc0oh21SPBiFdNmuZc7Xd0LZ/b4=,tag:vf07qDAHkskm/A+iyxfpaA==,type:str]
  ssh_private_key: ENC[AES256_GCM,data:P8MpYL7lvcuZJW2CbgrBqAMbB+l78QWPb91ncgh9PfnnHal1UR/qbD2do1C9j3p+2i7C7x6q3XPSUXPDLz9OZRDupQDSu9ovowwtrrKPOyWSfwQ0QhTd8lCR3r3PmHzJBggKSeK2fPEbH1e3/q/zMmbW8Xzq0sVh5qxJPvkA+z5/u9R62fw5Qr/vPWu/sXPl66+SuyubjSX0+d0ZWElmwyUR2EvdFKuOunQ98H1yDNSqCp2tOsLRcU7tMNh08FOSkKANmI/9aIXbqeq3L+G8Y2tC5voOPI8Hv9kLTuXz/cb+Um7mWXq12njJTfM5ZO3GzgI975RmftXuwndW/KykqghR5RMaVPEZbJ0iU3nXYI8nV89LjVyy4pjD/Q8KuieI9WSekY6KRFdDPX9Uup5w9hfFeV2UNGWXEt7P4TRB2OyA3YMGXFJOryeS49tYiDwLCg6lG4frRskxoefYZOjY3yDFxCYrPg0dAG2pleXeWZWb6wnjs62y6uJbHt85qOQDx2vBvzeXInoUm5UdgxDWYVCk0IIGlOXyNioWNx5+n3j/Q8Y=,iv:YLXrljHmIO66dVzws94sqyOI+oa2mxDYJsSRQpkKgQE=,tag:YkqvJJ7SazikphtVa+ozbQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRM1htbjQyTnVlWkRrOVR1
        Z1ZkeGxNR1BzdWZUZTl3WUx4L3NNTGpUTG1NCmFCNGV2TTJmelYzU3F4bCthWWxi
        c3ozdWhHNFpWL1JzZ0lwZHE2Z2ZDcm8KLS0tIDFTc0FPMFpCUUpoYld4OGZVZkNO
        Y09JaDRyd2J4MEdFaGQyeVpCTmhnRkEKYBNt15nWn2+IRxI0pNOgRyFF030jnj75
        YJd87tG+LyQ/6auBlVX3pcM8amsUWArkDHCUUNJDm4xifUUZaONWiw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gtjn7ra9z50kyzfxlnrthq44msj44tqgkyawafps450w820mk4vql8mgpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-21T12:07:54Z"
  mac: ENC[AES256_GCM,data:KqZ5iJgm0Se8vcUYxbYX4zpukRj+vWWyFUfVMSxsjrw4afM9aJHgqwby4XJDTOkcEznwA0wXOZBP/DgUMSZxX+60Z/WfjjP8qoVOIkiFUFR+wl97KloOm3v4EUuk6XhpURfxzFQZ661LkeYFvxKBY0NBSQcllgarmCxItaHuFK8=,iv:HCWiSwqXq/l5Tt4DLAHWAuilSbjNVt3AnhNodaThdTs=,tag:gusbgIZXgMLiCdGqRZu7bQ==,type:str]
  version: 3.13.1
