apiVersion: v1
kind: Secret
metadata:
  name: homeassist-config
  namespace: homeassistant
type: Opaque
stringData:
  configuration.yaml: |
    homeassistant:
      name: Home
      latitude: 51.0000
      longitude: 5.0000
      elevation: 0
      unit_system: metric
      time_zone: Europe/Amsterdam
      auth_providers:
        - type: trusted_networks
          trusted_networks:
            - 192.0.2.0/24
          trusted_users:
            192.0.2.0/24:
              - "00000000000000000000000000000000"
          allow_bypass_login: true
        - type: homeassistant

    default_config:

    http:
      ip_ban_enabled: false
      login_attempts_threshold: 5
