apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: kairos-kubevirt-evaluation
    home-server.dev/evaluation: kairos
  name: kairos-agent-user-data
  namespace: vms
stringData:
  userdata: ENC[AES256_GCM,data:jLs5zoXtiKm5ZjJpRu2KHVonbFFNaLKqJyjAPlTE1Qam0I607oSh8bBUT6/RVBGKylMLCJmBkMkBuwJNWYQWqH7dVRN4og4VJSf6ppxA1KsxcP439PawzMxj3LgqZJ4tBuYxzKCXFEUiE/Bg/bwDMsmGx6Z+icUkkmPyeF872z7NzkGN1ykHIW2TW3jcYcYjm/zvkHmsdJPoL1rH9/+Dq/QpCuT0ciydc8c3+E0nS9BnFBANbyZ0MsQHlWBN1jh5BurulEirbRY25Qiib28EAlGwdO0BR0INOCCd4pQsXWa3kPI/Yi4GSFwJJRvD1CaBwkSaxf4WbMPnftbfCXejHAdLCC7hDm/mhlvK7mm+qiaZkGg02kJtcPiZ7048BO1olel4OA71nvhxoK4Hl2Bl3wdWZczW35YRGBGGrbnqxmbuP5zNDB1XahJJyLsMQlbczopPveDOtsHDgoNxQVc51WiP9sM2/b4pkzFtAMkdkblcBJTuSRPvGH7WQt+bU+ywMAymVJ25AF+l5/N14/LVIJmIayOr190fjGvr85xLKtfkMC5eCg3dx240Jw==,iv:V7wsrHZyJFbKnvewUk2BSUkMju1MQZQZvFL/k1i9dvU=,tag:LN1XBOIdTPqGs59CvBT3Ow==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZmNMMmluUG9JU0k1bzFs
        NlZ0cUhXZ3M4RE5ack95UXFIYzBRWFZsMmp3Ck0xYTd3Qk5zb1ZBdDduanIzSElW
        MVJsS2QzSkxheEpwNU9FbkZWRWprd2cKLS0tIDJpK2NidjhkT3dXRGE3K1djQ3BN
        eTc0ZEtBUDZrMzNhVFNEQ2IvVTlLdTAKfkEQTwPNUmqryZkOATqZr6HZ2AZooyGP
        0dvdQDlJ5+28G7DzHKBFC+3El9xHMvr/fx9Wt2g6oikzuED7D8GRMg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gtjn7ra9z50kyzfxlnrthq44msj44tqgkyawafps450w820mk4vql8mgpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T09:27:46Z"
  mac: ENC[AES256_GCM,data:ZbKcDa/g5YrTTtw/5NRLA/IJUgVPU63uGRVOye+yInSiR5vxf5Olc8v6siSq7VGFgDRnR5ObOvSPuqPJxoFxBjE4r7jl02i65ZyOTHhURNKkR2cDjEFxN3/vKkGOzwpH4AsV2yexY/CSll1O1Oga0AhsGr4lZgmHnkhjB83YyJo=,iv:IdNwysas+YYC+VhVvei/xLd4S81u+P63w8CPGywIs54=,tag:6Wbulbhuo4BhxRHhTsgJ9w==,type:str]
  version: 3.13.1
