apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: kairos-kubevirt-evaluation
    home-server.dev/evaluation: kairos
  name: kairos-agent-user-data
  namespace: vms
stringData:
  userdata: ENC[AES256_GCM,data:KIbGortF5euquy/Cqs/AAcWuumwd8siedRFrMaItGX7SpkBAJTMDOszx1IfxdHcVDlqU7uB9AcNFDLfJjhxUlyRAb96ZWO+op96iXL+iAXDDKoILXjQNW5j9u1Kx3M6wOJ/jwgoe5nD5gP3cB4RXf6Be1ULyp0g939Hs3PQBMUU8HhlQ38OHMwTAO8m3PlkOfmZYO2bRHJapDkOQGK1+2LmPHAsJcSu3M5TuNFXiz6Idi7PYnFr/BsR85Sslh5T61Mnr6t6KPKYV1YOrYcM4XEoZ2PuroFwIqcG9GJsW/oTRM9HnwLgY8I2OdoRMJHisLKZR8D16HRt83muf3E0g8/8IAPJ+JxmPsD6WdoxPqTsJzErwZQ3aso7vwE1cT0AfPIvimk5rq0ySrynRMuhLVVTJmpm16G5S02AbCXZ5YiTGi68VFu1yZOW6BL1g+hX6HFMijZ3pWLvTwMeVK66Q2+lDerWL6ZrKoD+WjHVPt/XoKk4Xn4DIuBg3P+R142jqmwLnEVil+7rPpsZzuLYOYVQjJ/Zn9YBVSavVztyl3xSWbSfS06dvrvBUahlVTl4HdyC/IiaSWGalu1xOc9bRCO1poHSOIZLFyA3qsR3yhYVlBFLkJZcXh1VhkQNjOWZdV8y8hg2KrYAG6RcXW/R6Sib1GG0VrvZYIh6T2kjpn1HKMnvcgKdplJwbm4+Tw6yCMWk+Dbm3MU6+IP0GL6OEHSjaUXWcX1wbLYSnUUnQ63452iA2bsbQSFmHOlBkf05WbduhBDOn6zZyx/QbkF46VhULkOJ8z93MXDu1gQWqJllMw4HFVFjNKFLBfo3wRtxPGKYyE+EVhgLjU5xKay+s29g2n+S5/CnlG/flCwNJ94MAa3Ci7O+ICNPAiWgOcAgQgwsuZzIozTDRQLEeVZhMhSBfb/saZ23oWhoKs6Txp9vdItE8nY6WnPDB3Ok3EozSZZIvnxj5d2L7Or934x3uVAVqtaynZth40lnLsl4TDDXct4aqbiHs5WZNRfLMb9Wg3INLUe1mX6irUAfuswn4tVrmrGMUKdPjfoF/92vWNR8yqeeZ2DN/ZMsPFbPur1zzkQ9H1Oesg+lUReDFLTwOIl6LD7gj1gXgRDlBb4cd9BLGgQXMSdeGiAGH6rHQEeLRqhTDnErHNmb+4i+PFJE+hch4g9/NrVpxfJspx7bTkHAgwXBEYiwYufEzMbkHi9DMvVjbv2mujA7LLnjknnCqIKkkdc0kMj0pai2Yi6F8P7yzG1pG+9AWJesi7EZB4i6lZF/20NTwc2t/cYOsK8beY/dQ6KRO7NKUvc4Mj9FS+Tiqck/iUyrp1apwUixT3JG0pz8Q2bA8DBVPDolYEGo01mFEc8tnTHXzuMmi7sr9bk4hYbaaKClBH5in/m5ox279aVH1AA4iQ383RaKa6V4TmpbUE92YcaFdIy8iitDd/tQrKSt/2srCGkkBGqdw0rEwS6eP/5k6JI/brsY4fsbEG2J+0zAZR6u1A0cK89beJgLx59DAnVxSBVtbK8XG7GpS3PSdd+QvkoZ1HwFhhT1oZQiigFC7o7Fxvcc5IdEyB+zwGpbh4wNR7hQVrQUNfAWD1qWVa8Zt3iX4FZMeYg==,iv:iIwGDXA73PNH3ELob/u3kMJ+573RBIDU9209dEvzUVw=,tag:epZlaMVC432taLkHXzo43w==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q1VzVUp1YUpyRkZIb09T
        U0tXUm1FYTNnaVUrdjRhVVJ5UnAvamdQNVRFCitBdzNnOTdqZ09yREExWXVHQzRD
        WGhMZjVLTUlTTG5GdkZzN2NoM0NhZzgKLS0tIHZsUVhYQlN0MmJ0V0s1OWNwdms0
        QTJodzlaQ09Md0I0RG8xNXZBMXNDNlEKUCDs6l6bBiyohNALh9w1yOL27UOmwR7s
        IQsHICRCp0eBUFnLv6tU3a54tkK+egjnH99P9zm6PoyENc2dA9wpOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gtjn7ra9z50kyzfxlnrthq44msj44tqgkyawafps450w820mk4vql8mgpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T20:27:46Z"
  mac: ENC[AES256_GCM,data:RVicjBW2kxLpqGDhEU7sQOj6ComkcffTOYr4HQ9WVrN6ujVO7Q83lgcgatPIASfUf8MheGdnwCq9UcuoJQFOZ3vaAa0y8UwsWLnoHZI6h7HwnnCXxELsjiwrm05Ly/vIBXWnWwIN1X9MDQ8b6xjcKXf4llrtXxLY1DboYW6nFec=,iv:PwCeI4p+kLZNaiSnA8N927xp6YeExak9WTiFFla20Io=,tag:Kg9ShK4LqckY/vvFNyUeSw==,type:str]
  version: 3.13.1
