apiVersion: v1
data:
  values.yaml: ENC[AES256_GCM,data:UujKppdz8VTTASTr5+QuuvBKMaleUikoQi+rdv/xr10ZUZF8GvSN4qmMNG/nFLnVejXaatJ8OusOGKWc0/cqEl3VSdqKxG+u3sihEJxeWuDfQWxr1HLa2iJUwHMuuNYA24cAuffLdRGGl4RgHUrikox7Ig7LvvN/8mz7EA==,iv:20qfV3j+H1p14Vd3oxXkPppY1vlYj0j/BlihAQyVdQQ=,tag:J9EcO8dZxojpUBlBTU9Svw==,type:str]
kind: Secret
metadata:
  name: longhorn-admin-values
  namespace: longhorn-system
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVGVoUDNNRFJzYVhxc1dK
        dVR6TkdzZVFZUGNjRm1jY0dqeSszdE9ETWlRCkhjemg3aWI5RTIwSmFTU1F4eXhE
        NkV3bUVzQ2lXTHpUVXJRUm5kUHJidWcKLS0tIEdCT1BjSU0yNDJPNUI1TDFodEVp
        OWg1VTJUUFM4TUYwSGdGOXYwZlV1TFEK+4Ja6B3N246Ws631YuAZPCBWvZdTikPu
        u2f5eh/EWvAamdiNtp3TlxMfvAvgREWC0/823/FXsUHQtez1wsnPJQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gtjn7ra9z50kyzfxlnrthq44msj44tqgkyawafps450w820mk4vql8mgpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-18T20:59:16Z"
  mac: ENC[AES256_GCM,data:sAs/OQJdfYaLgNtxpvzVogGn6kKe+25mCsdRSyHGRLSyKC4ZUBlj/fnraqRFMZlrRLQrMR/jvPEIKL5bsjiRl5SLr/ENW6pqEA/Z8s0c/2opY6LjmoNjRUs4CHVWrnCgKSAEkoQyjazt8MBMe8b5Jg6AGGi5zG2KFnYANSiWJoM=,iv:WUYExYRmLbAohq9iozU32RgbKTEGZXaSqizRX3KtOVY=,tag:uxmyxrJQeaVgr4EzWY23Cw==,type:str]
  version: 3.13.0
