apiVersion: v1
data:
  values.yaml: ENC[AES256_GCM,data:z6biNPOMS3U/KZTxWpcZlRZuUPwFnZv9gnjANcXOEudzdc15TG3q5Tkyy1iLwVRvhT688QTprtbou4McIBfOdvwFy3b5qRyHtV+qQ+9C8FWjF4c5qgMRaIu9miMPFi0nr6vPTLFDBRbVBsUHUu/rXuNiXHukXRIltnixXw==,iv:yMnhcr03KBy4JrkitOxiEXMPSfvxPhYf22DYbuvLwTE=,tag:TZlS28b2LIsP2K+bNp0IOg==,type:str]
kind: Secret
metadata:
  name: longhorn-admin-values
  namespace: longhorn-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUnVKWW5NY3lWOTlxU1da
        VGlUcmFWaVl1RkVzdHlaRms2TVdVbDQvZkg0Cm5CbW5aOGVYWGJUWVJrZDRabk9J
        Mi9KbTRGcWxLOVUreXJoOW5xdkpvNjAKLS0tIGtrMkFNSWlpMWkyam9PWS91T1BF
        V2NDbFN5NzFkOTJycHk5NEFLbnRVeGcKdTQHOj4CxDZf5Gr+oWd1HoQ1UTMxBfpq
        NsZFsmriL9B4iH8PubmrIULuX9W6PRMz9TEZwlZorzX2Rd3N0+DEPg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gtjn7ra9z50kyzfxlnrthq44msj44tqgkyawafps450w820mk4vql8mgpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-18T21:10:44Z"
  mac: ENC[AES256_GCM,data:AKG7kC9Yce2VVvjfvylUce8yzu/f+0lVPBOy1xU/R8glK8or+KJjHfH/PSOorQ79C1R/LoaHuCqGCYLZY9x8fsnhfiWmphLXZY3AoSZZYbyacRqhFHFB9/xh9QIwfBTGYN88bNXNf9k+YDbc+v62hIIJCAM7vj0BME9ptnJ2N9c=,iv:2+BqTo/vkB1vQO+BuUn5benanMcePk8rnCHBXUGm8Tk=,tag:ebdzk5/90OTykVFSnZ/HIA==,type:str]
  version: 3.13.0
