apiVersion: v1
kind: Secret
metadata:
  name: prometheus-stack-private-values
  namespace: monitoring
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:pibiew7+TvhX4LOd84OwxdKhZFFyy9HfPF9XdsLAg/reD189q6MoxZX2rJeBAUsLl0Ug8bD7A9lPbvEa8TSxTfGSfqdL3mLlrYDfAGzx/3LyyiH0KAOcb6HKLNBSVXyYVLZlQvv32IreEEiWNLoAQzqhf+bMckl5uka9094uDdaYI3xH72MuTOdLLjJ1tq+RpNLVQkNcU9ktlxr7WZv6bEkKJWn4QWM0pz7pz2mcZI4/5q4uvnmQZ4jbM/06ZQyIxQyMzrV7OD7goASEK4EFzLIRITbvTZfUwZy/w+ChLXDjLYrZTlJk4xiRBT8C6YADZurDeBFocuP3GDkl7gncDfhZjQbrqfPNkR0CY7GQt8Z69QkhnlwYmLGcOtFSR9VE6IdAmMSaRr2Ad3RY9UtzwUTBb+XvONUNq/+v80qb4M5jrfsyEHyN9L2jrijeLHfJmylCJT+pLIK/mEuge1/NBEy8adKCjA13eafLWRf+UAI46tV/IAf7aEy7wmQxiz6QU9OL5usEz9T/shqZf9xHnN5hkgSMoN9lOliwot9cQRyLigTMdIIkBJ3o8v8PrtNJjMMBCbIM995lmTKKcNSISl7vgkyyKfTyZ98l1gABLTcA4W9nvMw3M72BuunJ7Y/GTq3FDN4gGKc98X+Woz/q5SS3DkinFL7DjDmQ0XuqsNaH06UnKUAqRvlSnGCrEwm3V+0UrMLZrjQ47x+j5zDy9mJx+ruKkQiYViCkKzYH19A2FtbKKRzYYoeu+UjtBxrA3LNXw67gkCv6F2UONZtX/27MbmWJM38/dA0yiteba4/8Vv9KXEGuppRgz8O62nI3z3N1Q3Kc/kB6HabB1ItpzKKnbtDrRZSZyzYgK75SxrRf1bE5cBAetCtfgtFzO8VsicnLJbvfmeKcEjOqM+K5UpQ0VJbfuiw2ovpu5v6iV4fPjuma3VJWX6kJLtYFLUQsIpmfnQKQh1tHUnvDs98C6/OvonmGvuA9/enviBvxJklKXlwRFN2MIFzLZCkJ4+gbxn2IDkxpijyirJ4Qrhw/c6Os51tZrtWYPsa1nPiRCwIvAjYW9FF0XYsm/lAzpv8XIwtM9P2W9YBn7RgxScT4/FBevjrDi1iZ5vjGJr1u08NA+IDq45dcCKEAeUP4LVoS+B/VGQ1FpwhbQxBxUjh5lJwWc5XmpHXQZsITL8v5/Fs=,iv:dJMdzkY7KtcMcssnw04DCDxKu4eJintR/gR0ctQuzxI=,tag:wF1i7w+X/LoT5jJuTX8bMg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdU13MGtzb05JYloxY3JY
        OWtXZ20vVnFVUGlnVk1tUndXVE16bFpnaFhVCitBdUlVYURranZnMzdEb2RFdWRD
        eWxqNnRhTEZJajJDRk50aFRLQ0w0TlUKLS0tIDc5b3FCcGV1SUkra0ZHTHliSzBX
        WWdhZW9sSm42WTlqdTk1V2Vnek5DR2MKhVNS1OPzWu5fUggv4VKMc/MjIgSfe7DX
        Iv9zLt1rR2qaSg8oVtR23MbGHTFw/9O6lstvKTnXBFuP2sux8RXRjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gtjn7ra9z50kyzfxlnrthq44msj44tqgkyawafps450w820mk4vql8mgpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-19T06:20:03Z"
  mac: ENC[AES256_GCM,data:G+0I0W7YEajBrlcMrMMgL44sGZ+seJfVM9+hQFq2gKT1KNQt7jZj1fqOPU7+0Q1LNlTNaK/w28Z62SRc+bUziJc+p0KG14xqWUqz8nnpJXnzZq4doUkeZr9Awg0C2U3ewbZnyXQf3HyZcKp7SWU1DgHfGRdDmh8r6q3tFY2HMdY=,iv:UAuyR6XGY2VwI+siDfwbKMQLMUVoLWkeKQmNvvsoWOM=,tag:nhJ3BOHLmvOviTDuXHzR6w==,type:str]
  version: 3.13.0
