apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-private-values
  namespace: auth
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:+ppTF7r7vTgntuUySPQidN9dOdM=,iv:KFMrD+283h8+nYJGmI8DfqiwWZP5SJpsvJ4RUhqeovc=,tag:k48gdOxc7cwHBUAlhtMPAA==,type:str]
  client-secret: ENC[AES256_GCM,data:HJKBj2k4lIlVSL8uCimBbbo6xRdM+Z3vnl4fyTTGg5GqZu+OYF83YA==,iv:tyEtYE8ErhPqfwhMYjyA0p/P2lqvh1+wwu2/+Q82maw=,tag:QsEKR0RCOx/r+IKSvkydpQ==,type:str]
  cookie-secret: ENC[AES256_GCM,data:06Uc+23SEXlCn4Yr2vpkC6wzZUNgvLjcdACM0fRyNEbHzPm99fsyjeWvQp0=,iv:F6qGoWCr9qbczJHcQ4iL+yekTkPDDpzncgckJnnjWJE=,tag:bfKWlC4VGik86KbFSeeAkQ==,type:str]
  values.yaml: ENC[AES256_GCM,data:7Gnj/LzYE6wxWidaqDraxf8MTyWNrDXmrugVTwiMMznPFSws1qd0LES1OWz9DZdXWShvI9IIGk5+M1CjBHQttElXymWBBg0i1z6bp+yn+Fi4oaDTehDrAD9C1xIHj7anK+H/JtNGCAlxRuoO/rZsEp3A6Ry8PH0vKagAXfcTyS7pz3fTrZxAX+x3iR5L7Bqp0hlfMGWg/hcUNZfNCLSzFL9A5VBqGYjc81heBIbKxIT8L/Spc81y7zU0WYnCWNCXnNAJK6r+MM3RVa+IyTNGst2vtLajOKOC1vwsURkRs8AfCNuodxE45IpV+1f16rUrijaYGmGJPSTag3OBVL53Dg/wEGWmV9ZytGJWpEMqY2bwg+lNnbcmlbnwnGkqJb2AbzrZr/NPbW+TuMi3wbInmfxnOWaL9y7g+OJ6dU3ZoRYqWwTJcya013PUuiplhHqg3ozgcTGtBBVsotONVDbe0mpBWIOdXmvizy04lR9qVwgjomSg76BVDF6xBjduZtEU+ESx00ZrKfs8IIC2/QRBm6AMjjnLLvceoeM81oOvWbjN9pibs/30O2QfsbgooY9lANq2bsBZb+pXtdJAUwb2fxAFJKmUDlU7fHGMxNy2g0V7/WT9/DYHaHAr8FCSaOzDKs9qbxPU0m0wRNuVf3rPlPXVrB66l1cFhSgi6HwvWyS+Q2z0TlD8+t7gCm9qKv9NA/WhNFYPTPUdB+D4irAPYnQ7DWd5b0m2CnfcMchsLeP70BSI19TQ74vlOi3KXDEKbwFI7UwZc8+hF/vPUeALmMw4Gx0=,iv:5lXkLkja8ZNnS3AfJKXp5WaEworYRK2g0x74IBFLT4g=,tag:G5ZYMDNsraScLrtiJkzy3Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTHhkL3hXeUIyemJ4ellx
        d3FpWERESHhBWGpXZVRFUzkvWE94Z0Nod2o4CktETFQ1bUZoMWJ6WFZNVFlRQTlv
        S0pMRklVQlJSYVo5Q1k4TlFiM3o2M28KLS0tIGJ6UDVpQlBzalZIRk1YSnZGM1U1
        TmtMdm4rdFd2bnd1ejdqM2UrWHFVS2sKY0g9D3ojilkXF06PgRf+UhDpbCHz+lJh
        nIu7woj2MnIW5knGUx+VgbNtuauIGO3lcJCRJCKYr1RLT94rOwSILQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gtjn7ra9z50kyzfxlnrthq44msj44tqgkyawafps450w820mk4vql8mgpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-18T20:47:08Z"
  mac: ENC[AES256_GCM,data:gBw4ZhhU1URAfC2B7qQLGWcao8wKEdcY3FPHUJXGUluqBCCqaPrRLguPoTanaq2H036jMZwLuuZIwSZIdQ/x6E9x3tfv+7yodSU7fvy0VUDfxgxBT+zjHReFBWTDW2YSLlIW+3j2Aj8aDiV6+YGdlyRHVa3yK/rjzlxQGQ8iY9A=,iv:DNqRjHcTxNGGRhq4Utw+PVqRx43ls+S7xiP++QdyZSk=,tag:+un7rgNgHyVX+ZvjV82MqA==,type:str]
  version: 3.13.0
