apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-private-values
  namespace: auth
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:Gbm3vSeZKGfqFjv0SzrKwspPpsK2pfFrARdDMiTmU+SkHO0=,iv:CsgibVgkjYrcUi4cSKi8cDChcRzrDqHdf6I1wvyNlDg=,tag:dWc0DFWa1GgbV86su3hWVA==,type:str]
  client-secret: ENC[AES256_GCM,data:jAqOeWVK5ZoYYE/NP+wJYLVst9yC6WrYwh1tK6rqdcuHREn8ekei,iv:HhrXElkj/ThaCAMxznLZvZM+WL8BHrVGb6e1MKBabs8=,tag:0cBM8043ISmt0IfFwAj7Ng==,type:str]
  cookie-secret: ENC[AES256_GCM,data:AncuLyNlU8qa26n56aGAWHC7pf9NvXEahwyZkk+wyh8Lemn2,iv:YAzkDXNkWFDMtueaWizp/keUzs+APUlENFL9l5xJGQ4=,tag:owrxmAURYsqP8lH4/trr2g==,type:str]
  values.yaml: ENC[AES256_GCM,data:JWkHKCDRyHRuNyaq9BZEJ5UzhPGApBML7mU0xWZ1eSKIm2Scbnw8LWSZkTIf0hxkLeuhy92JdS+pA5xxlJfPxTLqg/CaFGJcJ8o/YrOdxs5gyaXEb+ABjoq7JYN84YE9X7KgkzwbgKeFrJ09F1hUhqJGm81S00m6Pe+Ake/YjITAfIFVS0h0lInheCKXTCiy/guVRHjuGk9Qf4TlBmItMMjNE40r08pb6lD2CSHkbk+WiCytMeO5WkzF/zPa88eXGfoGHcFR12CEjuJ7xy5klmm/qQOEFA3F4iTjNdzoKq+tSJuN+SPOfn0QRi8ub0bGdWbClez4AqfmkwCmLDrc/FD3Xp2dCYNIOLi7OgahNsgkKEjItPLkLGQGcuS41OJSFJWK0UszF2I6xcFw97dSh5CGqccvZEsGehxINGIs08V++xXm+A6MEWsI1PvbJqPIV98GgNaotCR5WguOWfocGt/kGJ+9HMT5sRrVYfkV7rzYYBD+jFflfRI1ueSeonbXIfXctaUlCX0elhdWi+DraSLnmQtnA8gobO6YHAVFlJkPAK1OjOB4tORSR59joBncg7ZlZsJqP0SWvyx7/URHPwBi9TtQEtHAt+Fyc9XpTftxs10W0JN5gbTUk+lEnLEijS47M8ij0CV6eJj5Mc9Ht35sxkGfyj10GBa3+EeBte1fw5HwwA1pEFHbFwGBOMTEKmA/NeCfE0jT2XYkHNcR8EILklfwLvyzRc518WtVcN4gsKpROLNbnOVCCbnPpILZlyISJeQ6ypAhbOF7wfVeJYAq6tPt3iY2bsYp1Lo7V+4BOVlBhiUM9Hh9O+t6ExwSDyorOBNDuPEi82IXCQE/8WPPjyplyNMpDA1F/zowek+30gPFZ+wSqtNpXIfbv0Jf6Tp9,iv:qjSjP/Sdwrt64vnXodJiTlNGyS4pOF5bSUek2Xpw+g8=,tag:6vl/5ZQYEAE2YttNTycBHQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdC9KMGNlaXB2TUpUd1Uy
        Ly9lakZoektuanJxakpWZEhwZXBheHVHT2dVClFTOTVhOTJLNGt3amNTTkNRZzZt
        QXBLZG1mVTZTemlUUndNTUdNdVZjYUkKLS0tIGQrcHh1L3JnWUp1azE3OGNGQ0p0
        ZkJxSGY3c252NHU0NVVRdEhZaG0yRmMK0yGxWqab9PO1f+5YARPRnprPAk3WRzLm
        48QiyVkJwAOkJ3T4qdh7CcuS4IMCYAmo3/I3uju3rzD2y/idbxXP/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gtjn7ra9z50kyzfxlnrthq44msj44tqgkyawafps450w820mk4vql8mgpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-14T22:46:36Z"
  mac: ENC[AES256_GCM,data:74VqXw/YXauvVrhVpnBZy1DzjQnGQsPz3IrqxlSWoSJqpv8gQymEtusGiNGUrbv5F7JNQhqy3gZmYUviiDqvsew5P7sp5P4/bovJyHi9143F3dplMcApYgmlEImtSVF/l5oLP9FvOed/nrjelZtWiuFE0C/flep+J98u6U6xv/I=,iv:6Gol05Ogd4A1zuJZmloG/7mlxb5APo85h5BnmFQTwsU=,tag:p2CA2DjEOISRPOYEhpyqrg==,type:str]
  version: 3.13.0
