apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: homeassistant
spec:
  chart:
    spec:
      chart: ./application/home-assistant
      interval: 1h
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 30m
  maxHistory: 5
  releaseName: home-assistant
  timeout: 5m
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: homeassist-values
      valuesKey: values.yaml
