apiVersion: v1
kind: ServiceAccount
metadata:
  name: homelab-autoscaler-longhorn-safe-to-evict
  namespace: homelab-autoscaler-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homelab-autoscaler-longhorn-safe-to-evict
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - longhorn.io
    resources:
      - replicas
      - volumes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homelab-autoscaler-longhorn-safe-to-evict
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homelab-autoscaler-longhorn-safe-to-evict
subjects:
  - kind: ServiceAccount
    name: homelab-autoscaler-longhorn-safe-to-evict
    namespace: homelab-autoscaler-system
