apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pi-hole.fullname" . }}
  labels:
    {{- include "pi-hole.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pi-hole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pi-hole.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:v5.1.2
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: dnstcp
            containerPort: 53
            protocol: TCP
          - name: dnsudp
            containerPort: 53
            protocol: UDP
        env:
        - name: TZ
          value: "Europe/Amsterdam"
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pi-hole-admin
              key: web-password
        volumeMounts:
        - name: pihole-local-etc-volume
          mountPath: "/etc/pihole"
        - name: pihole-local-dnsmasq-volume
          mountPath: "/etc/dnsmasq.d"
      volumes:
      - name: pihole-local-etc-volume
        persistentVolumeClaim:
          claimName: pihole-local-etc-claim
      - name: pihole-local-dnsmasq-volume
        persistentVolumeClaim:
          claimName: pihole-local-dnsmasq-claim
