apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-local-dnsmasq-claim
spec:
  storageClassName: {{ .Values.storageClassName | quote }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi