apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi-hole.fullname" . }}
  labels:
    {{- include "pi-hole.labels" . | nindent 4 }}
spec:
  selector:
    app: pihole
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
  externalIPs:
  - {{ .Values.externalIp }}