apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: kairos-kubevirt-evaluation
    home-server.dev/evaluation: kairos
  name: kairos-agent-user-data
  namespace: vms
stringData:
  userdata: |
    #cloud-config
    hostname: kairos-agent
    install:
      auto: true
      device: /dev/vda
      reboot: true
    k3s:
      enabled: true
      args:
        - agent
        - --node-name=kairos-agent
        - --server=https://kairos-k3s-api.vms.svc:6443
        - --token=${KAIROS_K3S_TOKEN}
    users:
      - name: kairos
        lock_passwd: true
        groups:
          - admin
        ssh_authorized_keys:
          - ${PUBLIC_SSH_KEY}
type: Opaque
