domoticz:
  service:
    targetPort: 5005
  endpoint:
    ip: "192.168.254.123"
  ingress:
    hostnames:
      - "vendelier.bronneberg.org"

mail:
  service:
    targetPort: 21680
  endpoint:
    ip: "192.168.254.137"
  ingress:
    hostnames: 
      - "mail.bronneberg.org"
      - "mail.itsmyparty.nl"
      - "mail.myenglishplayground.nl"

photostation:
  service:
    targetPort: 5080
  endpoint:
    ip: "192.168.254.137"
  ingress:
    hostnames:
      - "photo.bronneberg.org"

apache:
  service:
    targetPort: 8088
  endpoint:
    ip: "192.168.254.123"
  ingress:
    hostnames:
      - "www.myenglishplayground.nl"
      - "myenglishplayground.nl"
      - "www.itsmyparty.nl"
      - "itsmyparty.nl"
      - "www.bronneberg.org"
      - "bronneberg.org"

opensprinkler:
  service:
    targetPort: 8080
  endpoint:
    ip: "192.168.254.130"
  ingress:
    hostnames:
      - "sprinkler.bronneberg.org"