domoticz:
  service:
    targetPort: 5005
  endpoint:
    ip: "192.0.2.121"
  ingress:
    hostnames:
      - "vendelier.bronneberg.org"

diskstation:
  service:
    targetPort: 5000
  endpoint:
    ip: "192.0.2.254"
  ingress:
    hostnames: 
      - "nas.bronneberg.org"

photostation:
  service:
    targetPort: 80
  endpoint:
    ip: "192.0.2.254"
  ingress:
    hostnames:
      - "photo.bronneberg.org"

apache:
  service:
    targetPort: 8088
  endpoint:
    ip: "192.0.2.121"
  ingress:
    hostnames:
      - "www.myenglishplayground.nl"
      - "myenglishplayground.nl"
      - "www.itsmyparty.nl"
      - "itsmyparty.nl"
      - "www.hhdx.nl"
      - "hhdx.nl"