apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.13.6
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 30m
  maxHistory: 5
  releaseName: cert-manager
  timeout: 5m
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    installCRDs: true
