apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "photobooth-api.fullname" . }}
  labels:
    {{- include "photobooth-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "photobooth-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "photobooth-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "photobooth-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.api.s3.secretName }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environment }}
            - name: BasePath
              value: {{ .Values.basePath }}
            - name: Logging__LogLevel__Microsoft__AspNetCore
              value: {{ .Values.logLevel.aspnetcore }}
            - name: Logging__LogLevel__Default
              value: {{ .Values.logLevel.default }}
          volumeMounts:
            - name: photobooth-db-volume
              mountPath: "/opt/app-root/data"              
          livenessProbe:
            httpGet:
              path: {{ .Values.basePath }}/health
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.basePath }}/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: photobooth-db-volume
        persistentVolumeClaim:
          claimName: photobooth-db-claim
