{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "photobooth-api.mongodbName" . }}
  labels:
    {{- include "photobooth-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP
  selector:
    {{- include "photobooth-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}
