{{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled (not .Values.mongodb.auth.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "photobooth-api.mongodbName" . }}-auth
  labels:
    {{- include "photobooth-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
stringData:
  {{ .Values.mongodb.auth.usernameKey }}: {{ .Values.mongodb.auth.rootUser | quote }}
  {{ .Values.mongodb.auth.passwordKey }}: {{ .Values.mongodb.auth.rootPassword | quote }}
{{- end }}
