{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "photobooth-api.mongodbName" . }}
  labels:
    {{- include "photobooth-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  serviceName: {{ include "photobooth-api.mongodbName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "photobooth-api.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "photobooth-api.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - name: mongodb
              containerPort: {{ .Values.mongodb.service.port }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data/db
          {{- with .Values.mongodb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if not .Values.mongodb.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
  {{- if .Values.mongodb.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        {{- $storageClassName := default .Values.storageClassName .Values.mongodb.persistence.storageClassName }}
        {{- if $storageClassName }}
        storageClassName: {{ $storageClassName | quote }}
        {{- end }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size }}
  {{- end }}
{{- end }}
