apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: 1.2.2
  install:
    remediation:
      retries: 3
  interval: 30m
  maxHistory: 5
  releaseName: longhorn
  timeout: 5m
  upgrade:
    remediation:
      retries: 3
