apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-retain
parameters:
  fromBackup: ""
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
  recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"*/30 * * * *", "retain":10},
                   {"name":"backup", "task":"backup", "cron":"0 * * * *", "retain":20}]'
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
