ingress:
  className: traefik
  host: fs.home.example
  middlewares:
    - default-redirect-https@kubernetescrd
    - auth-github-oauth@kubernetescrd


oauth2Proxy:
  enabled: false
  serviceName: oauth2-proxy
  endpointIP: 192.0.2.10
  path: /oauth2
  middlewares:
    - default-redirect-https@kubernetescrd
