apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: photobooth-api
  namespace: websites
spec:
  chart:
    spec:
      chart: ./application/photobooth-api
      interval: 1h
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 30m
  maxHistory: 5
  releaseName: photobooth-api
  timeout: 10m
  upgrade:
    remediation:
      retries: 3
