{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.resourceNames.deployment | default (include "home-assistant.fullname" .) }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: home-automation
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace }}
      ports:
        - port: {{ .Values.service.targetPort }}
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.monitoringNamespace }}
      ports:
        - port: {{ .Values.service.targetPort }}
          protocol: TCP
{{- end }}
