apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-admin
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: ./application/longhorn-admin
      interval: 1h
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 30m
  maxHistory: 5
  releaseName: longhorn-admin
  timeout: 5m
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: longhorn-admin-values
      valuesKey: values.yaml
